config/routes.rb
Rails.application.routes.draw do
  get 'pages/Home'
  get 'pages/About'
  get 'pages/FQA'
  get 'pages/lottery', as:  :lottery
  
  get 'pages/form'
  post 'pages/form2'

  get 'pages/admin'
   
  
  resources :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true , format: {with: /\A\d/} 
  before_save :content_upcase
  
  
  before_create do 
    self.content = title if content.blank?
  end 
  
protected
  def content_upcase
    content.try(:upcase!)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
  end

  def About
  end

  def FQA
  end
  
  def lottery
    render 'pages/lottery'
    @ball = (1..42).to_a.sample(6)
  end 
  
  def form2
    @name = params[:n]
    @bmi = params[:w].to_f/params[:h].to_f**2
  end
  
  
  def admin
    render layout: 'admin'
  end 
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index 
    @posts = Post.all 
  end
  
  def show  
    @post = Post.find(params[:id])
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_li name, url 
    content_tag :li, link_to(name, url)
  end 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/common/_navibar.html.erb
<ul>
  <li>  <a href="Home"> Home </a> </li>
  <li>  <a href="<%= pages_About_path%>"> About </a> </li>
  <li>  <%= link_to 'Lottery', lottery_path %>  </li>
  <%= nav_li 'Form', pages_form_path %>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Admin </title>

</head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "common/navibar" %>

<%= yield %>

</body>
</html>

app/views/pages/About.html.erb
<h1>Pages#About</h1>
<p>Find me in app/views/pages/About.html.erb</p>

app/views/pages/FQA.html.erb
<h1>Pages#FQA</h1>
<p>Find me in app/views/pages/FQA.html.erb</p>

app/views/pages/Home.html.erb
<h1>Pages#Home</h1>
<p>Find me in app/views/pages/Home.html.erb</p>

app/views/pages/admin.html.erb
<h1> ADMIN  </h1>

app/views/pages/form.html.erb
<h1> Form </h1>

<form action = "form2" method = "POST">
    名字 <input type="text" name="n" placeholder = "name" value = "蘇健豪">
    身高 <input type="text" name="h" placeholder = "height" value = "1.8">
    體重 <input type="text" name="w" placeholder = "weight" value = "65">
    
    <input type="text" name="authenticity_token">
    
    <input type="submit">
</form>


<form action = "form2" method = "POST">
    <input type="text" name="nickname" value = "XDDD">
    <input type="text" name="authenticity_token">
    <input type="submit">
</form>  </br>

<%= form_tag "form2", method: :POST do %>
  <%= text_field_tag :nickname %>
  <%= submit_tag %>
<% end  %>

app/views/pages/form2.html.erb
<%= params[:nickname] %>

<h1> form2 </h1>

<h2>Name: <%= @name %></h2>
<h2>BMI: <%= @bmi %></h2>


<%= debug params %>

app/views/pages/lottery.html.erb
<h1> Lottery </h1>

<ul>
    <% @ball.to_a.sample(6).each_with_index do  |ball, i|   %>
    <li> 第 <%= i+1 %> 顆球的號碼是 <%= ball %> </li>
    <% end %>
</ul>

app/views/posts/index.html.erb
<h1> Posts </h1>


<h1>List Posts</h1>

<ul>
  <% @posts.each do |post| %>
  <li><%= link_to post.title, post_path(post.id) %></li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<h1> Posts </h1>

<h1><%= @post.title %></h1>
<hr>
<p><%= @post.content %></p>

<%= link_to 'Back', posts_path %>